version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: flower-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL:-https://ra.nov.ru}
      - API_URL=${API_URL:-http://flower-backend:3000}
      - PORT=3000
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
      - /volume2/cert/fullchain.pem:/app/fullchain.pem
      - /volume2/cert/privkey.pem:/app/privkey.pem
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: flower-network
    external: true 